---
title: "Code chunks"
author: "Dr Brendan Palmer"
date: "2nd August 2019"
output:
  word_document: default
  html_document: default
---

It's good to give your chunks names, but don't give two chunks the same name

**Chunk: eval = FALSE**
```{r Chunk option 1a, eval = FALSE}

x <- c(1:10)

mean(x)

```


**Chunk: eval = TRUE**
```{r Chunk option 1b, eval = TRUE}

x <- c(1:10)

mean(x)

```


**Chunk: error = TRUE**
```{r Chunk option 2, error = TRUE}

x <- c(1:10)

mean(x)
mean(y)

```


**Chunk: include = FALSE**
```{r Chunk option 3a, include = FALSE}

x <- c(1:10)

mean(x)

```


**Chunk: include = TRUE**
```{r Chunk option 3b, include = TRUE}

x <- c(1:10)

mean(x)

```


**Chunk: echo = FALSE**
```{r Chunk option 4a, echo = FALSE}

x <- c(1:10)

mean(x)

```


**Chunk: echo = TRUE**
```{r Chunk option 4b, echo = TRUE}

x <- c(1:10)

mean(x)

```


**A few chunks**
```{r Chunk option 5, echo = FALSE, error = TRUE}

x <- c(1:10)

mean(x)
mean(y)
lmer(mpg ~ hp, data = mtcars)

```